const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.video,
		C3.Plugins.gamepad,
		C3.Behaviors.Flash,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.JavaScriptInEvents.Gameevent_Event22_Act1,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Gameevent_Event26_Act5,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SubInstanceVar,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.JavaScriptInEvents.Gameevent_Event135_Act7,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Gameevent_Event136_Act6,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.JavaScriptInEvents.Generalevent_Event51_Act7,
		C3.JavaScriptInEvents.Generalevent_Event52_Act6,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.OnKeyCode,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.JavaScriptInEvents.Generalevent_Event75_Act7,
		C3.JavaScriptInEvents.Generalevent_Event76_Act7,
		C3.JavaScriptInEvents.Generalevent_Event79_Act8,
		C3.JavaScriptInEvents.Generalevent_Event88_Act8,
		C3.JavaScriptInEvents.Generalevent_Event93_Act8,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Keyboard.Cnds.OnKeyCodeReleased,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.IsKeyCodeDown,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Audio.Acts.Preload
	];
};
self.C3_JsPropNameTable = [
	{Cursor: 0},
	{CursorHover: 0},
	{Rotate: 0},
	{SunRays: 0},
	{EndMusic: 0},
	{EndSound: 0},
	{FramePaused: 0},
	{AreaMusic: 0},
	{SliderMusic: 0},
	{TextPaused: 0},
	{AreaSound: 0},
	{FrameSound: 0},
	{SliderSound: 0},
	{FrameMusic: 0},
	{Fade: 0},
	{TextTapToPlay: 0},
	{TextGameOver: 0},
	{TextGameResults: 0},
	{TextTimeOver: 0},
	{Name: 0},
	{Frame: 0},
	{GuiBlocks: 0},
	{GuiLife: 0},
	{GuiScore: 0},
	{GuiTime: 0},
	{TextGameWon: 0},
	{Background: 0},
	{Sine: 0},
	{GameLogo: 0},
	{GameIcon: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Active: 0},
	{Timer: 0},
	{Damage: 0},
	{NormalSpeed: 0},
	{FastSpeed: 0},
	{FireSpeed: 0},
	{Bullet: 0},
	{Ball: 0},
	{PositionY: 0},
	{PositionX: 0},
	{PaddleType: 0},
	{Solid: 0},
	{Paddle: 0},
	{Mirrored: 0},
	{Cannon: 0},
	{CollisionGame: 0},
	{ID: 0},
	{MoveSpeedUp: 0},
	{Rocket: 0},
	{BallTrace: 0},
	{Bomb: 0},
	{Position: 0},
	{MoveSpeedDown: 0},
	{Barrier: 0},
	{LevelFont: 0},
	{LifeFont: 0},
	{FinalFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{MusicFont: 0},
	{SoundFont: 0},
	{LoadingFont: 0},
	{InfoFont: 0},
	{GameScoreFont: 0},
	{OrientationFont: 0},
	{BlocksFont: 0},
	{TotalScoreFont: 0},
	{BtnExit: 0},
	{BtnFullscreen: 0},
	{ButtonIndex: 0},
	{BtnPlay: 0},
	{BtnMenu: 0},
	{BtnMusic: 0},
	{BtnPause: 0},
	{BtnReload: 0},
	{BtnReturn: 0},
	{BtnSound: 0},
	{BtnStart: 0},
	{BtnGo: 0},
	{BtnRestart: 0},
	{BtnNextLevel: 0},
	{yes_obj: 0},
	{no_obj: 0},
	{CollisionDamage: 0},
	{TouchArea: 0},
	{Bonus: 0},
	{Reward: 0},
	{MaxDamage: 0},
	{BlockNumber: 0},
	{Block_1: 0},
	{Block_1_Piece_1: 0},
	{Block_1_Piece_2: 0},
	{Block_1_Piece_3: 0},
	{Block_1_Piece_4: 0},
	{Block_2: 0},
	{Block_2_Piece_1: 0},
	{Block_2_Piece_2: 0},
	{Block_2_Piece_3: 0},
	{Block_2_Piece_4: 0},
	{Block_3: 0},
	{Block_3_Piece_1: 0},
	{Block_3_Piece_2: 0},
	{Block_3_Piece_3: 0},
	{Block_3_Piece_4: 0},
	{Block_4: 0},
	{Block_4_Piece_1: 0},
	{Block_4_Piece_2: 0},
	{Block_4_Piece_3: 0},
	{Block_4_Piece_4: 0},
	{Block_5: 0},
	{Block_5_Piece_1: 0},
	{Block_5_Piece_2: 0},
	{Block_5_Piece_3: 0},
	{Block_5_Piece_4: 0},
	{IronBlock: 0},
	{Explosion: 0},
	{BonusBarrier: 0},
	{BonusCannons: 0},
	{BonusCloneBall: 0},
	{BonusFireball: 0},
	{BonusLife: 0},
	{BonusPaddleIncrease: 0},
	{BonusPaddleReduce: 0},
	{BonusScore: 0},
	{BonusSpeedBall: 0},
	{BonusTime: 0},
	{SizeWidth: 0},
	{SizeHeight: 0},
	{Coins: 0},
	{LevelCount: 0},
	{SpriteFont: 0},
	{LocalStorage: 0},
	{logo: 0},
	{pause_bg: 0},
	{popup_frame: 0},
	{info_btn: 0},
	{help: 0},
	{info_frame: 0},
	{info_close: 0},
	{help_frame: 0},
	{help_close: 0},
	{popup_txt: 0},
	{logo1: 0},
	{Gamepad: 0},
	{GameScoreFontTxt: 0},
	{overlay: 0},
	{Score_Frame: 0},
	{Buttons: 0},
	{TextFonts: 0},
	{Flash: 0},
	{Blocks: 0},
	{Physics: 0},
	{Pieces: 0},
	{MenuButtons: 0},
	{Balls: 0},
	{MaxBlocks: 0},
	{Lives: 0},
	{Score: 0},
	{Seconds: 0},
	{Minutes: 0},
	{CountScore: 0},
	{CountSeconds: 0},
	{rv_ad_enabled: 0},
	{rv_popup: 0},
	{TriggerPopupValue: 0},
	{RV_index: 0},
	{pause_popup_updown: 0},
	{game_index: 0},
	{pause_index: 0},
	{rv_popup_updown: 0},
	{MaxLevels: 0},
	{Level: 0},
	{TotalScore: 0},
	{Pause: 0},
	{Fullscreen: 0},
	{Sound_db: 0},
	{Sound_Slider: 0},
	{Sound_Volume: 0},
	{Music_db: 0},
	{Music_Slider: 0},
	{Music_Volume: 0},
	{GAME_NAME: 0},
	{SelectedIndex: 0},
	{menu_index: 0},
	{popup_updown: 0},
	{CanChangeValue: 0},
	{username: 0},
	{game_slug: 0},
	{GameOver_Updown: 0},
	{gameover_index: 0},
	{gamewon_index: 0},
	{GameWon_Updown: 0}
];

self.InstanceType = {
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	SunRays: class extends self.ISpriteInstance {},
	EndMusic: class extends self.ISpriteInstance {},
	EndSound: class extends self.ISpriteInstance {},
	FramePaused: class extends self.ISpriteInstance {},
	AreaMusic: class extends self.ISpriteInstance {},
	SliderMusic: class extends self.ISpriteInstance {},
	TextPaused: class extends self.ISpriteInstance {},
	AreaSound: class extends self.ISpriteInstance {},
	FrameSound: class extends self.ISpriteInstance {},
	SliderSound: class extends self.ISpriteInstance {},
	FrameMusic: class extends self.ISpriteInstance {},
	TextTapToPlay: class extends self.ISpriteInstance {},
	TextGameOver: class extends self.ISpriteInstance {},
	TextGameResults: class extends self.ISpriteInstance {},
	TextTimeOver: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	GuiBlocks: class extends self.ISpriteInstance {},
	GuiLife: class extends self.ISpriteInstance {},
	GuiScore: class extends self.ISpriteInstance {},
	GuiTime: class extends self.ISpriteInstance {},
	TextGameWon: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Ball: class extends self.ISpriteInstance {},
	Paddle: class extends self.ISpriteInstance {},
	Cannon: class extends self.ISpriteInstance {},
	CollisionGame: class extends self.ITiledBackgroundInstance {},
	Rocket: class extends self.ISpriteInstance {},
	BallTrace: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Barrier: class extends self.ITiledBackgroundInstance {},
	LevelFont: class extends self.ISpriteFontInstance {},
	LifeFont: class extends self.ISpriteFontInstance {},
	FinalFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	MusicFont: class extends self.ISpriteFontInstance {},
	SoundFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	InfoFont: class extends self.ISpriteFontInstance {},
	GameScoreFont: class extends self.ISpriteFontInstance {},
	OrientationFont: class extends self.ISpriteFontInstance {},
	BlocksFont: class extends self.ISpriteFontInstance {},
	TotalScoreFont: class extends self.ISpriteFontInstance {},
	BtnExit: class extends self.ISpriteInstance {},
	BtnFullscreen: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnMenu: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnReload: class extends self.ISpriteInstance {},
	BtnReturn: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BtnStart: class extends self.ISpriteInstance {},
	BtnGo: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnNextLevel: class extends self.ISpriteInstance {},
	yes_obj: class extends self.ISpriteInstance {},
	no_obj: class extends self.ISpriteInstance {},
	CollisionDamage: class extends self.ISpriteInstance {},
	TouchArea: class extends self.ISpriteInstance {},
	Block_1: class extends self.ISpriteInstance {},
	Block_1_Piece_1: class extends self.ISpriteInstance {},
	Block_1_Piece_2: class extends self.ISpriteInstance {},
	Block_1_Piece_3: class extends self.ISpriteInstance {},
	Block_1_Piece_4: class extends self.ISpriteInstance {},
	Block_2: class extends self.ISpriteInstance {},
	Block_2_Piece_1: class extends self.ISpriteInstance {},
	Block_2_Piece_2: class extends self.ISpriteInstance {},
	Block_2_Piece_3: class extends self.ISpriteInstance {},
	Block_2_Piece_4: class extends self.ISpriteInstance {},
	Block_3: class extends self.ISpriteInstance {},
	Block_3_Piece_1: class extends self.ISpriteInstance {},
	Block_3_Piece_2: class extends self.ISpriteInstance {},
	Block_3_Piece_3: class extends self.ISpriteInstance {},
	Block_3_Piece_4: class extends self.ISpriteInstance {},
	Block_4: class extends self.ISpriteInstance {},
	Block_4_Piece_1: class extends self.ISpriteInstance {},
	Block_4_Piece_2: class extends self.ISpriteInstance {},
	Block_4_Piece_3: class extends self.ISpriteInstance {},
	Block_4_Piece_4: class extends self.ISpriteInstance {},
	Block_5: class extends self.ISpriteInstance {},
	Block_5_Piece_1: class extends self.ISpriteInstance {},
	Block_5_Piece_2: class extends self.ISpriteInstance {},
	Block_5_Piece_3: class extends self.ISpriteInstance {},
	Block_5_Piece_4: class extends self.ISpriteInstance {},
	IronBlock: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	BonusBarrier: class extends self.ISpriteInstance {},
	BonusCannons: class extends self.ISpriteInstance {},
	BonusCloneBall: class extends self.ISpriteInstance {},
	BonusFireball: class extends self.ISpriteInstance {},
	BonusLife: class extends self.ISpriteInstance {},
	BonusPaddleIncrease: class extends self.ISpriteInstance {},
	BonusPaddleReduce: class extends self.ISpriteInstance {},
	BonusScore: class extends self.ISpriteInstance {},
	BonusSpeedBall: class extends self.ISpriteInstance {},
	BonusTime: class extends self.ISpriteInstance {},
	Coins: class extends self.ISpriteInstance {},
	LevelCount: class extends self.ITextInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	logo: class extends self.IWorldInstance {},
	pause_bg: class extends self.ISpriteInstance {},
	popup_frame: class extends self.ISpriteInstance {},
	info_btn: class extends self.ISpriteInstance {},
	help: class extends self.ISpriteInstance {},
	info_frame: class extends self.ISpriteInstance {},
	info_close: class extends self.ISpriteInstance {},
	help_frame: class extends self.ISpriteInstance {},
	help_close: class extends self.ISpriteInstance {},
	popup_txt: class extends self.ITextInstance {},
	logo1: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	GameScoreFontTxt: class extends self.ITextInstance {},
	overlay: class extends self.ISpriteInstance {},
	Score_Frame: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	TextFonts: class extends self.ISpriteInstance {},
	Blocks: class extends self.ISpriteInstance {},
	Bonus: class extends self.ISpriteInstance {},
	Pieces: class extends self.ISpriteInstance {},
	MenuButtons: class extends self.ISpriteInstance {}
}